version: "3.7"
services:

    db:
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_DB: autoqa
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: automated@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 1234
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8081:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

    autoqa_backend:
        image: autoqa_backend        
        ports:
            - "8005:8005"
        depends_on:
            - db
        command: ["sh", "-c", "python Root/manage.py migrate && python Root/manage.py runserver 0.0.0.0:8005"]
volumes:
    db-data:
    pgadmin-data:
